CREATE TABLE roles (
    role_id int PRIMARY KEY generated by default as identity,
    name VARCHAR ( 50 ) UNIQUE NOT NULL
);

CREATE TABLE items (
    item_id int PRIMARY KEY generated by default as identity,
    role_id int references roles(role_id) NOT NULL,
    name VARCHAR ( 150 ) NOT NULL,
    price int
);

INSERT INTO roles VALUES ('Я');
INSERT INTO items VALUES (1, 'milk', 350);
INSERT INTO items VALUES (1, 'bread', 50);